# Generated by Django 3.1.3 on 2020-11-20 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(help_text='实体和关系识别模块的输入文本的MD5值。', max_length=32, verbose_name='输入')),
                ('res', models.TextField(help_text='实体和关系识别模块的输出结果。', verbose_name='输出')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='默认为当前时间。', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '结果',
                'verbose_name_plural': '结果',
                'ordering': ['-created_time'],
            },
        ),
    ]
